#!/usr/bin/env python3
"""Generate docs/settings-map.md — owner/path/key-count map for every GSettings schema.

Parses all *.gschema.xml (schemas/, modules/*/schemas/, modules/*/*/schemas/,
migrations/schemas/), maps each schema id to its owning module from modules.js
(by directory) plus SUB_SCHEMAS declarations in each module extension.js, and
flags migration-only legacy shims.

Usage: python3 tools/gen-settings-map.py
Writes docs/settings-map.md. No arguments, deterministic output.
"""
import glob
import os
import re
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

# module uuid -> dir (from modules.js MODULES table)
mod_txt = open('modules.js', encoding='utf-8').read()
MODULES = re.findall(r"uuid:\s*'([^']+)'", mod_txt)

# schema id -> subsystem reader (from SUB_SCHEMAS in each module extension.js)
SUB_OWNERS = {}  # schema id -> (module dir, subsystem key)
for mod in MODULES:
    ext = f'modules/{mod}/extension.js'
    if not os.path.exists(ext):
        continue
    txt = open(ext, encoding='utf-8', errors='replace').read()
    m = re.search(r'SUB_SCHEMAS\s*=\s*\{(.*?)\};', txt, re.S)
    if not m:
        continue
    for sm in re.finditer(r"(\w+):\s*'([^']+)'", m.group(1)):
        SUB_OWNERS[sm.group(2)] = (mod, sm.group(1))

rows = []
for f in sorted(glob.glob('schemas/*.xml')
                + glob.glob('modules/*/schemas/*.xml')
                + glob.glob('modules/*/*/schemas/*.xml')
                + glob.glob('migrations/schemas/*.xml')):
    root = ET.parse(f).getroot()
    for sch in root.findall('schema'):
        sid = sch.get('id')
        path = sch.get('path')
        keys = sch.findall('key')
        nkeys = len(keys)
        # owner: module dir containing the file, or suite root
        if f.startswith('modules/'):
            owner = f.split('/')[1]
        elif f.startswith('migrations/'):
            owner = 'migrations (legacy shim)'
        else:
            owner = 'suite root'
        sub = SUB_OWNERS.get(sid, ('', ''))[1]
        # types breakdown
        types = {}
        for k in keys:
            t = k.get('type') or ('enum:' + (k.get('enum') or '?'))
            types[t] = types.get(t, 0) + 1
        tstr = ', '.join(f'{v}x{t}' for t, v in sorted(types.items()))
        rows.append((owner, sid, path, nkeys, sub, f, tstr))

rows.sort(key=lambda r: (-r[3], r[1]))
total = sum(r[3] for r in rows)

short = lambda s: s.replace('org.gnome.shell.extensions.', '')
lines = []
lines.append('# Settings Map — schema owner/path/key inventory')
lines.append('')
lines.append('> Auto-generated by `python3 tools/gen-settings-map.py`. Do not edit by hand.')
lines.append('> Regenerate after any schema change.')
lines.append('')
lines.append(f'Total: **{len(rows)} schemas, {total} keys** across 5 suite modules + migration shims.')
lines.append('')
lines.append('| Owner module | Schema id | dconf path | Keys | Subsystem reader | File |')
lines.append('|---|---|---|---|---|---|')
for owner, sid, path, nkeys, sub, f, _ in rows:
    lines.append(f'| {owner} | {short(sid)} | `{path}` | {nkeys} | {sub or "—"} | `{f}` |')
lines.append('')
lines.append('## Notes')
lines.append('')
lines.append('- One schema id maps to exactly one dconf path. Key names may repeat across')
lines.append('  schemas (e.g. `cpu-refresh-time` in both system-monitor schemas) but they are')
lines.append('  independent settings under different paths — no conflict.')
lines.append('- `system-monitor` (old, 107 keys) is kept only for one-shot migration into')
lines.append('  `system-monitor-next-applet` (see `subsystems/system-monitor/migration.js`).')
lines.append('  Runtime reads the `-next-applet` schema exclusively.')
lines.append('- Files under `migrations/schemas/` are legacy shims read once by `migrations.js`')
lines.append('  (`panel-clone`, `topbar-panel-controls`, old `gnome-customizer-manager`).')
lines.append('  Do not add new keys there.')
lines.append('- Per-monitor / per-hardware keys keep upstream defaults, never snapshotted:')
lines.append('  `panel-element-positions`, `panel-lengths`, `panel-anchors`,')
lines.append('  `panel-visible` (connector-id JSON) and `primary-monitor` (empty = auto).')
lines.append('  A fresh machine generates its own layout for its own monitors.')
lines.append('- `migration-*` guard keys in the suite schema keep default `false` so fresh')
lines.append('  installs re-run migrations.')
lines.append('')
lines.append('## Type breakdown per schema')
lines.append('')
lines.append('| Schema id | Keys | Types |')
lines.append('|---|---|---|')
for owner, sid, _, nkeys, _, _, tstr in rows:
    lines.append(f'| {owner} / {short(sid)} | {nkeys} | {tstr} |')
lines.append('')

os.makedirs('docs', exist_ok=True)
with open('docs/settings-map.md', 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines))
print(f'WROTE docs/settings-map.md: {len(rows)} schemas, {total} keys')
